#!/bin/sh

set -e

lb config noauto \
	--architectures i386 \
	--debian-installer live \
	--distribution stretch \
	--apt apt \
	--mirror-bootstrap http://debian.mirrors.ovh.net/debian/ \
	--mirror-binary http://debian.mirrors.ovh.net/debian/ \
	--mirror-chroot http://debian.mirrors.ovh.net/debian/ \
	--mirror-debian-installer  http://debian.mirrors.ovh.net/debian/ \
	--binary-images iso-hybrid \
	--chroot-filesystem squashfs \
	--memtest none \
	--updates false \
	--archive-areas "main contrib non-free" \
	--bootappend-live "locales=fr_FR.UTF-8 keyboard-layouts=fr username=poutoux boot=live quiet splash" \
	"${@}"
