#!/bin/sh

set -e

lb config noauto \
	--architectures i386 \
	--debian-installer live \
	--apt apt \
	--mirror-bootstrap http://debian.mirrors.ovh.net/debian/ \
	--mirror-chroot-security http://security.debian.org/ \
	--mirror-binary http://debian.mirrors.ovh.net/debian/ \
        --mirror-binary-security http://security.debian.org/ \
	--mirror-chroot http://debian.mirrors.ovh.net/debian/ \
	--mirror-debian-installer  http://ftp2.fr.debian.org/debian/ \
	--binary-images iso-hybrid \
	--chroot-filesystem squashfs \
	--memtest none \
	--updates false \
	--iso-volume="Poutoux" \
	--archive-areas "main contrib non-free" \
	--bootappend-live "locales=fr_FR.UTF-8 keyboard-layouts=fr username=poutoux boot=live quiet" \
	"${@}"
